# How to use NumPy

## What is Numpy?

* **NumPy**.
    * The underlying library specialized for **fast** vector and matrix calculations in Python.
* Major libraries other than Numpy
    * Machine learning libraries
        * scikit-learn
        * Keras + TensorFlow
    * Computation and visualization libraries
        * Scipy
        * Pandas
        * matplotlib

### Numpy Fast Processing

In [1]:
# import the necessary libraries
import numpy as np
import time
from numpy.random import rand

# Size of rows and columns
N = 200

# Initialize the matrix
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# Calculate using Python lists

# Get start time
start = time.time()

# Perform matrix multiplication using a for statement
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("Calculation results using only Python functions：%.2f[sec]" % float(time.time() - start))

# Calculate using NumPy

# Get start time
start = time.time()

# Perform matrix multiplication using NumPy
matC = np.dot(matA, matB)

# NumPy is displayed as 0.00[sec] because it is terminated at the second decimal place
print("Calculation results when using NumPy：%.2f[sec]" % float(time.time() - start))

Calculation results using only Python functions：8.82[sec]
Calculation results when using NumPy：0.06[sec]


## NumPy 1D array

### import
* How to import NumPy (customary naming convention)
    * **import NumPy as np**
    
### 1D array
* **ndarray**
    * Classes for fast array handling
    * **how to create instances
        * **np.array(list)`**
            * create an instance with each element of a list as an array element
        * **`np.range(X)`**
            * Create an instance with array elements of increasing and decreasing values at equal intervals

In [3]:
import numpy as np

## Example of generating by list using np.array() function
## Generate so that the result is data1 = [1 2 3]
data1 =
print("data1 =", data1)

## Example of generating using np.range() function
data2 = np.arange(4)
print("data2 =", data2)

## Example of generating using np.range() function - Part 2
## Generate using np.range() so that data3 = [1 3 5 7 9]
data3 =
print("data3 =", data3)

SyntaxError: invalid syntax (872615617.py, line 5)

* How to call arrays by dimension
    * 1D: vector
        * Example: `array_1d = np.array([1,2,3,4,5,6,7,8])`
    * 2 dimension: matrix
        * Example: `array_2d = np.array([[1,2,3,4],[5,6,7,8]])`
    * 3 or more dimensions: tensor
        * Example: `array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])`

### Calculation for 1D arrays
* Element-wise computation
    * Python lists
        * Write a loop to take out elements one by one and calculate
    * ndarray
        * Arithmetic operations between ndarrays are calculated on elements in the same position
        * No need to write a loop

In [ ]:
# Run without NumPy
storages = [1, 2, 3, 4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

# Run with NumPy
import numpy as np
storages = np.array([1, 2, 3, 4])
#Calculate to [2 4 6 8] in one line
print(storages)

[2, 4, 6, 8]
[2 4 6 8]


### Index References and Slices
* Index references and slices are also available in NumPy
    * Same as Python's list type
    * To change the value of a slice, use **`arr[start:end] = the value you want to change***.
        * Note that a list of (end - 1) is created from start

In [ ]:
arr = np.arange(10)
print(arr)

# Change to [1 1 3 4 5 6 7 8 9] on one line
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 3 4 5 6 7 8 9]


### ndarray
notes* If you change the value of a variable to which you assign a value, the value of the original ndarray array is also changed.* Same as Python lists* If you want to copy an ndarray into two separate variables, use the copy() method.

In [1]:
import numpy as np

# Let's see how it behaves if we assign the ndarray directly to another variable
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = arr1
arr2[0] = 100

# Changes to another variable are affecting the original variable
print(arr1)
print(arr2)
print("If you use copy()")
# Let's see how it behaves when an ndarray is assigned to another variable using copy( )
arr1 = np.array([1, 2, 3, 4, 5])

# Use copy() to avoid influence
arr2[0] = 100

# Changes to another variable have no effect on the original variable
print(arr1)
print(arr2)

[1 2 3 4 5]
[100   2   3   4   5]


### view and copy
* Differences between Python lists and ndarrays
    * A slice of ndarray points to the same data as the **original array (view)**.
** If you want to treat a slice as a copy, use **`arr[:].copy()`**.

In [14]:
import numpy as np

# Let's see how Python behaves with slices in a Python listing
arr_List = [x for x in range(10)]
print("List type data.")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

print("リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません")
print("arr_List:",arr_List)
print()

# Let's see how NumPy's ndarray behaves with slices
arr_NumPy = np.arange(10)
print("NumPy ndarray data.")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("The NumPy slice assigns the view (information about where the data is stored), so changes in arr_NumPy_view are reflected in arr_NumPy.")
print("arr_NumPy:",arr_NumPy)
print()

# Let's check the behavior when copy() is used with NumPy's ndarray
arr_NumPy = np.range(10)
print('This is the behavior when copy() is used with NumPy's ndarray')
print("arr_NumPy:",arr_NumPy)
print()
# Create a new nested array using copy() so that arr_Numpy is not affected.

arr_NumPy_copy[0] = 100

print("arr_NumPy_copy does not affect arr_NumPy because a copy() is used to generate a copy")
print("arr_NumPy:",arr_NumPy)

リスト型データです
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

NumPyのndarrayデータです
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

NumPyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます
arr_NumPy: [100   1   2   3   4   5   6   7   8   9]

NumPyのndarrayでcopy()を用いた場合での挙動です
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]


### Boolean index reference
* How to retrieve elements using an array of Boolean (True/False) values in \[ \}

In [ ]:
import numpy as np

arr = np.array([2, 4, 6, 7]) 
### True, True, True, False, so indices 0 to 2 are output
print(arr[np.array([True, True, True, False])])  

[2 4 6]


* If the remainder when divided by 3 is 1, True -> output

In [ ]:
import numpy as np

arr = np.array([2, 4, 6, 7]) 

print("Array of boolean values whether the remainder of dividing each element of arr by 3 is 1 or not")
print(arr % 3 == 1)

print("Array of arr elements whose remainder when divided by 3 is 1")
print(arr[arr % 3 == 1])

arrの各要素を3で割ったときの余りが1かどうかの真偽値の配列
[False  True False  True]
3で割ったときの余りが1となるarrの要素の配列
[4 7]


### Universal Functions
* Function that returns the result of an operation on each element of an ndarray array
    * Available for multidimensional arrays
    * One argument
        * np.abs()
            * returns the absolute value of an element
        * np.exp()
            * returns the power of e (base of natural logarithm) of the element
        * np.sqrt()
            * returns the square root of the element
    * two arguments
        * np.add()
            * returns the sum of elements
        * np.subtract()
            * returns the difference of two elements
        * np.maximum()
            * returns an array containing the maximum value of the elements

In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# In one line, make each element of variable arr an absolute value and assign it to variable arr_abs

print(arr_abs)

# Output the power and square root of e for each element of variable arr_abs in one line


[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


### Set Functions
* Set functions work only with 1D arrays
* Typical functions
    * np.unique()
        * remove duplicates and sort
    * np.union1d(x, y)
        * take elements that exist in at least one of the arrays x and y and sort (union set)
    * np.intersect1d(x, y)
        * take common elements from arrays x and y and sort (product set)
    * np.setdiff1d(x, y)
        * remove elements common to arrays x and y from array x and sort (difference set)

### Random Numbers
* Typical random number generation functions
    * np.random.rand()
        * Generates uniform random numbers between 0 and 1**.
        * Generates a random number by an integer argument.
    * np.random.randint(x, y, z)
        * Generate z integers that are greater than or equal to x and less than or equal to y** * Generate z integers
        * Allows tuples to be entered for z
            * For (2,3) → generate a 2x3 matrix
    * np.random.normal()
        * Generate random numbers following Gaussian distribution
  
  
* Import method
    * **from numpy.random import randint**
        * only **randint()** will be available at function call time
    * Generalize: "**from module name import function name in that module**"

In [5]:
import numpy as np

## Use np.random.rand() to print out an array of 5 elements, each of which is greater than or equal to 0 and less than 1
print("=== np.random.rand() ===")

## Use np.random.randint() to output a 3x4 matrix of integers between 1 and 10
print("=== np.random.randint() ===")


## Print an array of 5 elements using np.random.normal()
print("=== np.random.normal() ===")

=== np.random.rand() ===
[0.52982126 0.9048857  0.71280572 0.45405227 0.92187386]
=== np.random.randint() ===
[[2 1 4 3]
 [9 9 9 2]
 [9 3 9 5]]
=== np.random.normal() ===
[ 0.57659509  1.64729356 -0.35863837 -0.39121826  0.32242266]
HelloWord


## NumPy 2-dimensional array
### 2-dimensional array
* How to create a 2-dimensional array (= matrix)
    * **np.array(\[ list, list \])**
* **ndayyay array.shape**
    * **return the number of elements per dimension
* **ndarray array.reshape(a, b)**
    * Convert to a matrix of the same shape as the given arguments

In [1]:
import numpy as np

## Prepare two lists
arr1 = [1, 2 ,3]
arr2 = [4, 5, 6]

## generate ndarray array using two lists

print(np_arr)

## Output a matrix with the number of rows and columns changed to 3⋆2 using reshape

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### 7.3.2 Index References and Slices
* One index is specified → any row is retrieved as an array
* Specify two indexes → get individual elements
    * Expression (both refer to the same element)
        * **arr\[1\]\[2\]**
        * **arr\[1, 2\]**
* Slices can also be used

In [15]:
import numpy as np

arr = np.array([[1, 2 ,3], [4, 5, 6]])
# Output [1 2 3]
print(arr[1])
# Output [2]
print(arr[1,2])
## Output the first row, column 1 and beyond.
print(arr[1,1:])  

[4 5 6]
6
[5 6]


### axis
* axis
    * Like a coordinate axis
    * In the case of a 2-dimensional array
        * axis = 0
            * process every column
        * axis = 1
            * Perform processing for each row

* For sum() method
    * no argument specified
        * simple sum
    * axis = 0 for the argument  
        * Addition is performed vertically (in the column direction) and output as a 1-dimensional array
    * axis=1 for the argument
        * The values are added horizontally (in the row direction) and output as a 1D array.

In [ ]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])

## Output simple sums

## Output the result vertically

## Output the result horizontally

21
[5 7 9]
[ 6 15]


### Fancy Index Reference
* Fancy index references
    * A function that returns a sub-array (copy) when an array (ndarray, list, etc.) is put into an index
        * Note that the expression method is different from that of index references
        * Index number is specified starting from the 0th
    * Unlike slices, always returns a copy of the original data and creates new elements

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) 

# Extract the elements of the rows in the order of line 3, line 2, and line 0, and output the new elements created
# Index numbers start from 0


[[7 8]
 [5 6]
 [1 2]]


### Transposed matrix
* transpose
    * Transposing rows and columns
    * How to transpose an ndarray
        * Using np.transpose(ndarray array)
        * Using ndarray array.T

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
print("===arr===")
print(arr)

## Print the transposed variable arr
print("======")

## Print the output using np.transpose
print("======")
print(np.transpose(arr))

=== arr ===
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
=== arr.T ===
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
=== np.transpose(arr)) ===
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Sorting
* ndarray can be sorted by sort() as well as list type
    * In the case of a 2-dimensional array
        * **`ndarray array.sort(0)`**
            * elements are sorted by column
        * **`ndarray array.sort(1)`**
            * elements are sorted by rows
        * The above would radically change the original sequence.
    * **`numpy.sort(ndarray array.sort(1)`** also sorts elements by row
        * differs from ndarray array.sort() in that it returns a copy of the sorted array (the original array remains unchanged).
    * If ``axis'' is not specified, 2-dimensional arrays are sorted by rows.
* **`argsort()`** method
    * returns the index of the array after sorting

In [ ]:
import numpy as np

arr = np.array([[15, 30, 5, 10],[9, 12, 3, 6],[4, 2, 8, 6]])

print("====arr====")
print(arr)
print()

## Print the result of sorting by numpy.sort()
print("====np.sort()====")
print(np.sort(arr))
## The original matrix is not affected
print("====arr====")
print(arr)
print()

## print the result of sorting by columns

print("====arr.sort()====")
print(arr)

## Print the result of sorting by rows

print("====arr.sort()====")
print(arr)

====arr====
[[15 30  5 10]
 [ 9 12  3  6]
 [ 4  2  8  6]]

====np.sort(arr)====
[[ 5 10 15 30]
 [ 3  6  9 12]
 [ 2  4  6  8]]
====arr====
[[15 30  5 10]
 [ 9 12  3  6]
 [ 4  2  8  6]]

====arr.sort(0)====
[[ 4  2  3  6]
 [ 9 12  5  6]
 [15 30  8 10]]
====arr.sort(1)====
[[ 2  3  4  6]
 [ 5  6  9 12]
 [ 8 10 15 30]]


#### argsort example
* Array before sorting: **\[15, 30, 5\]**
* array after sorting: **\[5, 15, 30\]**
    * Zero th (5) of the array after sorting: * Second of the original array
    * 1st (15) of array after sort: 0th of original array
    * Second of the array after sorting (30): first of the original array

In [16]:
import numpy as np

arr = np.array([15, 30, 5])
arr.argsort()

array([2, 0, 1], dtype=int64)

### Matrix calculations* Functions for matrix calculations.
* **`np.dot(a, b)`**
* return the matrix product of two matrices
* Matrix product: a matrix whose elements are inner products of row and column vectors in the matrix
* Matrix product example

            
            
$$
        \begin{bmatrix}
        1 & 2 \\
        3 & 4 \\
        \end{bmatrix}
    \times
    \begin{bmatrix}
    1 & 2 \\
    3 & 4 \\
    \end{bmatrix}
    = 
    \begin{bmatrix}
    1 \times 1 + 2 \times 3 & 1 \times 2 + 2 \times 4 \\
    1 \times 3 + 4 \times 3 & 3 \times 2 + 4 \times 4 \\
    \end{bmatrix}
    = 
        \begin{bmatrix}
        7 & 10\\
        15 & 22 \\
        \end{bmatrix}
$$
            

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

## Print the result of the matrix product calculation
print("=== np.dot() ===")


arr3 = np.array([1, 2])

## Calculate the norm
print("=== np.linalg.norm(arr3) ===")
print(np.linalg.norm(arr3))

=== np.dot(arr1, arr2) ===
[[ 7 10]
 [15 22]]
=== np.linalg.norm(arr3) ===
2.23606797749979


### statistical functions
* statistical functions
    * Functions or methods that perform mathematical operations on an entire ndarray array or around a specific axis
    * Method examples
        * **`mean(), np.average()`**
            * return the average of the array elements
            * mean() allows specifying the data type at the time of calculation
            * np.average() can be used to obtain a weighted average by giving a weight parameter as an argument
        * **`np.max(), np.min()`**
            * **`np.max(), np.min() return maximum and minimum values
        * **`np.argmax(), np.argmin()`**
            * return maximum and minimum index numbers * **`np.argmax(), np.argmin()
        * **`np.std(), np.var()`**
            * return standard deviation and variance
    * ** can be processed for each axis specified by ``axis'' * **`axis = 0
        * **`axis = 0`**
            * process by columns
        **`axis = 1`**
            * process by row **`axis = 1`** * process by row

In [ ]:
import numpy as np

arr = np.array([[1, 2 ,3], [4, 5, 6]])

print("=== arr ===")
print(arr)

### print the result of finding the overall mean
print("=== arr.mean() ===")

### Output the results of the column-wise averages.
print("=== arr.mean() ===")

### Output the result of the row-by-row average.
print("=== arr.mean() ===")


=== arr ===
[[1 2 3]
 [4 5 6]]
=== arr.mean() ===
3.5
=== arr.mean(axis=0) ===
[2.5 3.5 4.5]
=== arr.mean(axis=1) ===
[2. 5.]


## Vector
### magnitude of vector
* np.linalg.norm() method
* Function to calculate the norm.
* If you pass an array as an argument, it will calculate it like other NumPy functions.

In [ ]:
import numpy as np
array = np.array([1, 3])
# Output the vector magnitude of the array

3.1622776601683795


## Matrices.
Addition and subtraction are

(variable name + variable name)

(variable name - variable name)

In [8]:
import numpy as np
A=np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
# Output the matrix added together

# Output the matrix subtracted


[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


### Scalar Multiplication
If you write a number in a vector, it will be output multiplied by a scalar

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
# Output scalar times A


### Product of Matrices
The np.dot() method can be used to find the product of matrices

In [2]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
# Output the inner product of matrix A and matrix B


SyntaxError: invalid syntax (1346167272.py, line 2)

The product or quotient of two matrices is

(variable name*variable name)

(variable name/variable name)

The product and quotient of the matrices are obtained by

In [10]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
# Output the product of matrix A and matrix B


[ 4 10 18]


In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
# Output the quotient of matrix A and matrix B


Matrices of different shapes can also be obtained with np.dot()

*There is a condition that must be satisfied in order to find the product of matrices of different shapes.

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [-1, -2, -3]])
B = np.array([[4, -4], [5, -5], [6, -6]])
# Output the inner product of matrix A and matrix B
